/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts,scss}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d0e1fb",
        "background": "#f7f9fb",
        "primary": "#3525cd",
        "secondary-fixed": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed-dim": "#bec6e0",
        "primary-container": "#4f46e5",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#4d44e3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed": "#131b2e",
        "tertiary-fixed": "#dae2fd",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "tertiary-container": "#586076",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#c3c0ff",
        "error": "#ba1a1a",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#d4dbf5",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "outline": "#777587",
        "secondary": "#505f76",
        "tertiary": "#41485e",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-lg": "1.5rem",
        "gutter": "1rem",
        "space-2xl": "2rem",
        "margin-sm": "1rem",
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "margin": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "title-md": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0.005em", "fontWeight": "600" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-lg": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-lg": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "label-md": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-xl": ["2rem", { "lineHeight": "2.5rem", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "body-md": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-sm": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.03em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
